### PR TITLE
Little update

### PR DESCRIPTION
**Pull request by iamflorencejay**
1. Renaming folders to of course, to end confusion on where the folders are.
2. Updated readme and makefile.

### CODE REVIEW

**Comment by s9260** [comment]
I have a couple reasons for not merging this:
1. You broke the app's launch.json with 905cda4 9e328f9 and 6de4c75. `DebugServer: Cannot zip package: missing manifest file in "Odysee-Roku/out/.roku-deploy-staging"`. I use launch.json a lot for development, so it would be nice if it wasn't broken.
2. You changed the license from GPLv3 to MIT with 83ca9ad67eaff42721fb3c2a76eeee30e31be5f6. While I can respect standardization across the board for Odysee's apps, I would rather not have the license changed right now.
3. You didn't delete the leftover folders for the trending generator or the original app folder.

**Comment by s9260** [comment]
I would be more than happy to merge the changes you made regarding the readme, however.

**Comment by s9260** [comment]
I'm also not against the renaming of the folders to something better either, I just think that the build files that go along with them should be updated as well.

5eab4cf (dev) will eventually come to master along with the changes to the folder names as well. I might have to remove a lot of the legacy UI code from dev as well. I'm not at all satisfied with how the current (legacy) UI item selection method works right now.

In the long term, I will also have to repurpose some old code I wrote a couple weeks ago that experimented with abusing Tasks to create a multithreader for Roku (1000 basic threads with data in->out takes around 2.374 seconds), but it has problems with synchronization once it is a Task itself, which might force me to make it a separate scene instead. Not sure how I would synchronize between scenes, but it would be nice to have for search or quite literally anything that needs to be ran more than once.

**Comment by iamflorencejay** [comment]
Sorry late reply. I will fix this later.

**Comment by iamflorencejay** [comment]
@s9260 LBRY is on MIT license, so I've just copied it to any other projects here on LBRY.

**Pull request closed without merging**
